


import { Acessos, CheckboxStates } from '../../../data/dataTypes'

type Props = {
  acesso: Acessos,
  setCheckboxStates: (value: CheckboxStates | ((prevState: CheckboxStates) => CheckboxStates)) => void
}

export default function SetCheckboxStates({ acesso, setCheckboxStates }: Props) {
  if (acesso) {
    setCheckboxStates((prevState) => ({
      ...prevState,
      agencias: acesso.agencias!,
      aliquotas_irrf: acesso.aliquotas_irrf!,
      antecipacao_prorrogacao_vencimentos: acesso.antecipacao_prorrogacao_vencimentos!,
      arquivo_config: acesso.arquivo_config!,
      atos: acesso.atos!,
      bancos: acesso.bancos!,
      baixa_automatica: acesso.baixa_automatica!,
      baixa_manual: acesso.baixa_manual!,
      beneficiarios_fiscais: acesso.beneficiarios_fiscais!,
      calculo: acesso.calculo!,
      camaras_adicionais: acesso.camaras_adicionais!,
      cancelamento_reativacao_documentos: acesso.cancelamento_reativacao_documentos!,
      cadastro_geral: acesso.cadastro_geral!,
      cadastros_gerais: acesso.cadastros_gerais!,
      campos_adicionais: acesso.campos_adicionais!,
      cartorios: acesso.cartorios!,
      coberturas: acesso.coberturas!,
      competencias: acesso.competencias!,
      condicoes_parcelamento: acesso.condicoes_parcelamento!,
      configuracao_boletos: acesso.configuracao_boletos!,
      configuracao_cancelamento_boletos: acesso.configuracao_cancelamento_boletos!,
      configuracao_guia_boletos: acesso.configuracao_guia_boletos!,
      configuracao_inscricao_boletos: acesso.configuracao_inscricao_boletos!,
      configuracao_pagamentos_boletos: acesso.configuracao_pagamentos_boletos!,
      configuracoes_economicas: acesso.configuracoes_economicas!,
      configuracoes_imoveis: acesso.configuracoes_imoveis!,
      configuracoes_notas_avulsas: acesso.configuracoes_notas_avulsas!,
      configuracoes_receitas_diversas: acesso.configuracoes_receitas_diversas!,
      construtoras: acesso.construtoras!,
      contribuicoes_melhoria: acesso.contribuicoes_melhoria!,
      contribuintes: acesso.contribuintes!,
      controle_saldo_devedor: acesso.controle_saldo_devedor!,
      creditos_tributarios: acesso.creditos_tributarios!,
      declaracao_iss_homologado: acesso.declaracao_iss_homologado!,
      desmembramentos: acesso.desmembramentos!,
      documentos: acesso.documentos!,
      documentos_config: acesso.documentos_config!,
      economicos: acesso.economicos!,
      enderecos: acesso.enderecos!,
      englobados: acesso.englobados!,
      engenheiros: acesso.engenheiros!,
      estorno_inscricao: acesso.estorno_inscricao!,
      feriados: acesso.feriados!,
      fontes_divulgacao: acesso.fontes_divulgacao!,
      formulas: acesso.formulas!,
      geoprocessamento: acesso.geoprocessamento!,
      geoprocessamento_config: acesso.geoprocessamento_config!,
      gerenciador_economico: acesso.gerenciador_economico!,
      guias: acesso.guias!,
      horarios_funcionamento: acesso.horarios_funcionamento!,
      imoveis: acesso.imoveis!,
      imoveis_config: acesso.imoveis_config!,
      imobiliarias: acesso.imobiliarias!,
      indexadores: acesso.indexadores!,
      inscricao_divida: acesso.inscricao_divida!,
      integracao_contabil: acesso.integracao_contabil!,
      integracao_lancamentos_config: acesso.integracao_lancamentos_config!,
      integracoes_contabeis_config: acesso.integracoes_contabeis_config!,
      junta_comercial_config: acesso.junta_comercial_config!,
      livros_divida_ativa: acesso.livros_divida_ativa!,
      limites_arrecadacao: acesso.limites_arrecadacao!,
      manutencao_divida: acesso.manutencao_divida!,
      manutencao_pagamentos: acesso.manutencao_pagamentos!,
      materiais_servicos: acesso.materiais_servicos!,
      motivos: acesso.motivos!,
      naturezas_texto_juridico: acesso.naturezas_texto_juridico!,
      notas_avulsas: acesso.notas_avulsas!,
      notas_avulsas_config: acesso.notas_avulsas_config!,
      obras: acesso.obras!,
      obras_config: acesso.obras_config!,
      parcelas: acesso.parcelas!,
      parcelamento_credito: acesso.parcelamento_credito!,
      planta_valores: acesso.planta_valores!,
      receitas_diversas: acesso.receitas_diversas!,
      receitas_diversas_config: acesso.receitas_diversas_config!,
      requerimento_manutencao_lancamento: acesso.requerimento_manutencao_lancamento!,
      tabelas_calculo: acesso.tabelas_calculo!,
      taxas_expediente_config: acesso.taxas_expediente_config!,
      termos_abertura_encerramento_livro: acesso.termos_abertura_encerramento_livro!,
      tipos_documentos: acesso.tipos_documentos!,
      transferencia_imoveis: acesso.transferencia_imoveis!,
      transferencia_imoveis_config: acesso.transferencia_imoveis_config!,
      unidades_medida: acesso.unidades_medida!,
      viabilidade: acesso.viabilidade!
    }))
  }
}
